
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author
 */
public class BarraEstadistica extends javax.swing.JPanel {
private Lienzo objeto=new Lienzo(this);
protected int numero1Y;
protected int numero2Y;
protected int numero3Y;
protected Color c1;
protected Color c2;
protected Color c3;


    /**
     * Creates new form BarraEstadistica
     */
    public BarraEstadistica() {
        initComponents();
        objeto.setSize(500,350);
        objeto.setLocation(0,0);
        this.add(objeto);
        
    }
    public void setColorBarra1(Color c){
    
        objeto.setBackground(c);
        c1=c;
    }
    public Color getColorBarra1(){
        return objeto.c;
    }
    public void setColorBarra2(Color c){
    
        objeto.setBackground(c);
        c2=c;
    }
    public Color getColorBarra2(){
        return objeto.c;
    }
    public void setColorBarra3(Color c){
    
        objeto.setBackground(c);
        c3=c;
    }
    public Color getColorBarra3(){
        return objeto.c;
    }
    public void setBarra1Y(int n){
    numero1Y=n;
    }
    public int getBarra1Y(){
    return numero1Y;
    }
    public void setBarra2Y(int n){
    numero2Y=n;
    }
    public int getBarra2Y(){
    return numero2Y;
    }
    public void setBarra3Y(int n){
    numero3Y=n;
    }
    public int getBarra3Y(){
    return numero3Y;
    }
    /*public void cargarBarras(){
    objeto.cargarBarras();
    }*/
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
